### ISSUE TITLE
Find the best location to inject server info to the routing handler

### ISSUE THREAD

**Issue by stevehu** [networknt/light-java#11]
Light-Java is designed to work with swagger specification to generate the code and trigger scope verification in security and validation in validator. However, this make injection of common services with is not defined in the service swagger specification hard to be injected and by pass all the swagger validation. Need to find a way to inject server info which is the endpoint that output all information about components wired in and their configuration.

**Comment by AmaranthLIS** [comment]
Yes, if project generated by swagger we can't add other handlerProviders like info/healthy ...
Even if add new handlerProvider to com.networknt.server.HandlerProvider
But it is so need!

**Comment by stevehu** [comment]
Two months ago, I have tried to inject the a separate path with /server/info and a specific scope to control who can access it in SwaggerHandler. It is working but I just don't feel good about it. One problem with this is the final url is dynamic as the API/service swagger spec might have v1 or v2 as base path and it is not predictable. We need a static server info url so that it can be called from portal. I am working on the service registry and discovery now and hoping to let the server to send notification to portal once it is up and running with full path of server info url just like it register itself with Consul or Zookeeper. The other way to work our is inject a handler into the call chain to bypass swagger, validation etc. It is doable but pretty messy as call chain is dynamic per API/service. I am open to any ideas or recommendations at the moment and will come back to this issue soon as this is needed for production like you said.

**Comment by AmaranthLIS** [comment]
In this cause i really don't know how better it do...
I can offer this way: add PATH an exception for swagger-validation which get from config. 
HandlerProvider is manually added routing (for example /server/info).

**Comment by stevehu** [comment]
This is the approach I was taking but due to the dependency of base path in the original swagger spec, the server/info might have /v1 or /v2 or some other prefixes. Also, you don't need to by pass the validation and security as when you inject something the scope and other validation constraints will be in. I am hoping I will have answers once service registry is completed and see if we can let server to register the server/info endpoint on consul or zookeeper.

**Comment by stevehu** [comment]
Tried to convert ServerInfoHandler to middleware so that it can be put into the middleware chain. It works but it doesn't make sense that every request must go through ServerInfoHandler to check it the uri is matched. It is too much overhead just for this simple common API.

**Comment by stevehu** [comment]
The next step is to secure the endpoint so that only light-portal can access it.

**Comment by stevehu** [comment]
The final decision is to put it into swagger-codegen to inject security for server info and an endpoint to specification in the preprocessing phase. It works pretty well and this can be a common ways to add other common endpoints in the feature. The server info handler is renamed so that it can match the same name generated. The import statement is change the template to point the handler to the one in light-java instead.
