### ISSUE TITLE
Alternate Config impls ... S3, http?

### ISSUE THREAD

**Issue by mwnorman** [networknt/light-java#28]
The (default) com.networknt.config module implements a file-based config-properties system.
Any idea how hard it would be to re-implement using S3 or some other mechanism (like HTTP
to an external server)?

**Comment by stevehu** [comment]
If you look into the code, it is based on SPI so other implementations can be plugged in easily. I don't have S3 access but I have plan to implement config on consul and zookeeper as we've already using them for service registry and discovery.

**Comment by stevehu** [comment]
#29
