### ISSUE TITLE
Config server not read

### ISSUE THREAD

**Issue by AmaranthLIS** [networknt/light-java#49]
I have this cause (with version 1.2.7):
i've generated project by swagger, changed port in src/main/resources/config/server.json but port not change! Then i thought for change port need use param httpPort but it not help too.
Actually light-java framework has own server.yml (*.yml config is more priority) and my app not read my server.json

It's look like bug, is not?

**Comment by stevehu** [comment]
From version 1.2.6, light-java supports yml, yaml and json. If you want to change port, you need to copy server.yml into config directory. Otherwise, the default server.yml in server module will be used. Basically you need to use yml to overwrite default config files.

**Comment by AmaranthLIS** [comment]
I make sense (after read source light-java).
May be say about priority config files to documentation? And swagger-code generate change to create server.yml instead of server.json (it's so confusing)

**Comment by stevehu** [comment]
Yes. The document is not updated yet. I am going to do that soon and you can help to review. The latest swagger-codegen generate server.yml already. Thanks for pointing out this issue.

**Comment by AmaranthLIS** [comment]
Thanks Steve!

**Comment by stevehu** [comment]
@AmaranthLIS I have updated the config document and published it. Please review and let me know if anything need to be added/updated/clarified. Thanks a lot and happy coding.

https://networknt.github.io/light-java/other/config/

**Comment by AmaranthLIS** [comment]
Reviewed that all correct.
Indeed thank @stevehu !
It's really helpful for everyone!
